releases:
  - name: flux-operator
    chart: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
    version: 0.60.0
    namespace: flux-system
    createNamespace: true
    hooks:
      - events: [postsync]
        command: kubectl
        args:
          - apply
          - -f
          - clusters/kind/flux-system/flux-instance.yaml