apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
  labels:
    kuma.io/sidecar-injection: enabled
  annotations:
    kuma.io/mesh: demo
---
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: demo
spec:
  mtls:
    backends:
      - name: ca-1
        type: builtin
        dpCert:
          rotation:
            expiration: 1d
        conf:
          caCert:
            RSAbits: 2048
            expiration: 10y
    enabledBackend: ca-1
  networking:
    outbound:
      passthrough: false
  routing:
    localityAwareLoadBalancing: true
    zoneEgress: true
  skipCreatingInitialPolicies:
   - '*'
---
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: container-patch-1
  namespace: kuma-system
spec:
  initPatch:
    - op: add
      path: /securityContext/runAsNonRoot
      value: "false"
---
apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
  name: metrics-default
  labels:
    kuma.io/mesh: demo
spec:
  taragetRef:
    kind: Dataplane
    labels:
      app.kubernetes.io/name: kube-state-metrics
  default:
    sidecar:
      includeUnused: true
      profiles:
        appendProfiles:
        - name: Basic
    backends:
    - type: Prometheus
      prometheus:
        port: 5670
        path: "/metrics"
    applications:
    - name: kube-state-metrics
      path: /metrics
      port: 8080
      