apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: observability
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: observability
spec:
  interval: 1m0s
  chart:
    spec:
      chart: kube-state-metrics
      version: 5.30.1
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
  releaseName: kube-state-metrics
  targetNamespace: observability
  valuesFrom:
  - kind: ConfigMap
    name: flux-kube-state-metrics-config
    valuesKey: kube-state-metrics-config.yaml
---
apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
  name: metrics-default
  namespace: kuma-system
  labels:
    kuma.io/mesh: demo
spec:
  targetRef:
    kind: Dataplane
    labels:
      app.kubernetes.io/name: kube-state-metrics
  default:
    sidecar:
      includeUnused: true
      profiles:
        appendProfiles:
        - name: Basic
    backends:
    - type: Prometheus
      prometheus:
        port: 5670
        path: "/metrics"
    applications:
    - name: kube-state-metrics
      path: /metrics
      port: 8080