apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: httpbin
resources:
- httpbin.yaml
- netshoot.yaml
- sa.yaml
- externalservice.yaml
- generated-external-services.yaml
# - tunnel.yaml