apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: httpbin
resources:
- httpbin.yaml
- netshoot.yaml
- sa.yaml
- externalservice.yaml
- generated-external-services.yaml
- mesh-traffic-permissions.yaml
- generated-mesh-traffic-permissions.yaml
- advanced-mesh-traffic-permissions.yaml
- role-based-mesh-traffic-permissions.yaml
# - tunnel.yaml
- mongosh-deployment.yaml
- kyverno-meshpassthrough-policy.yaml
- kyverno-meshpassthrough-rbac.yaml
- mongodb-passthrough.yaml
- kyverno-meshpassthrough-postman-policy.yaml
- meshpassthrough-postman-echo.yaml