apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-meshpassthrough
  annotations:
    policies.kyverno.io/title: Restrict MeshPassthrough Resources
    policies.kyverno.io/category: Security
    policies.kyverno.io/subject: MeshPassthrough
    policies.kyverno.io/description: >-
      This policy allows any MeshPassthrough in namespaces with pp.hqy.io/solution=zcor.
      Namespaces with any other value for pp.hqy.io/solution are restricted to MongoDB Atlas only.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: restrict-mongodb-only-for-non-zcor-solutions
    match:
      any:
      - resources:
          kinds:
          - MeshPassthrough
    context:
    - name: namespace
      apiCall:
        urlPath: "/api/v1/namespaces/{{ request.namespace }}"
    preconditions:
      all:
      - key: "{{ namespace.metadata.labels.\"pp.hqy.io/solution\" || 'not-found' }}"
        operator: NotEquals
        value: "not-found"
      - key: "{{ namespace.metadata.labels.\"pp.hqy.io/solution\" || 'not-found' }}"
        operator: NotEquals
        value: "zcor"
    validate:
      message: "In namespaces with pp.hqy.io/solution label (non-zcor values), MeshPassthrough must only target MongoDB Atlas domains with TLS on port 27017 or Postman Echo with TLS on port 443"
      anyPattern:
      - metadata:
          labels:
            kuma.io/mesh: demo
        spec:
          default:
            passthroughMode: Matched
            appendMatch:
            - type: Domain
              value: "*.*.mongodb.net"
              protocol: tls
              port: 27017
      - metadata:
          labels:
            kuma.io/mesh: demo
        spec:
          default:
            passthroughMode: Matched
            appendMatch:
            - type: Domain
              value: "postman-echo.com"
              protocol: tls
              port: 443
