apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
spec:
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        args:
        - sleep
        - infinity
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netshoot
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: netshoot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: badnetshoot
spec:
  selector:
    matchLabels:
      app: badnetshoot
  template:
    metadata:
      labels:
        app: badnetshoot
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        args:
        - sleep
        - infinity
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: badnetshoot
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: badnetshoot
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-httpbin-org
  namespace: httpbin
  labels:
    kuma.io/mesh: demo
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/service: httpbin
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        kuma.io/service: netshoot_httpbin_svc_80
    default:
      action: Allow
---
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: demo
metadata:
  name: httpbin
  namespace: kuma-system
spec:
  tags:
    kuma.io/service: httpbin
    kuma.io/protocol: tcp # optional, one of http, http2, tcp, grpc, kafka
  networking:
    address: httpbin.org:443
    tls: # optional
      enabled: false
---
apiVersion: kuma.io/v1alpha1
kind: MeshPassthrough
metadata:
  name: wildcard-passthrough
  namespace: httpbin
  labels:
    kuma.io/mesh: demo
spec:
  targetRef:
    kind: Dataplane
    labels:
      app: netshoot
  default:
    passthroughMode: Matched
    appendMatch:
    - type: Domain
      value: "httpbin.org"
      protocol: tcp
      port: 443
