---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example3