apiVersion: v1
kind: Namespace
metadata:
  labels:
    test.cluster.local/label: test
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: kong-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: httpbin
spec:
  interval: 1m0s
  path: ./app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system