apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kuma
  namespace: kuma-system
spec:
  interval: 1m0s
  url: https://kumahq.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kuma-mesh
  namespace: kuma-system
spec:
  interval: 1m0s
  timeout: 2m
  chart:
    spec:
      chart: kuma
      version: 2.10.5
      sourceRef:
        kind: HelmRepository
        name: kuma
  releaseName: kuma-mesh
  targetNamespace: kuma-system
  values:
    controlPlane:
      logLevel: debug
      envVars:
        KUMA_RUNTIME_KUBERNETES_INJECTOR_CONTAINER_PATCHES: "container-patch-1"
    ingress:
      enabled: true
    egress:
      logLevel: debug
      enabled: true
